version: "3"
services:
    backend:
        build: .
        restart: always
        ports:
            - 9000:9000
        environment:
            PYTHONUNBUFFERED: 0
            POSTGRESS_HOST: database
        links:
            - "database:database"
        depends_on:
            - database
        networks:
            - backend-network
        volumes: 
            - ../datas/images:/app/media
    database:
        image: postgres
        container_name: database
        restart: always
        environment:
            - POSTGRES_HOST_AUTH_METHOD:trust 
        ports:
            - 5432:5432
        volumes: 
            - ../datas:/var/lib/postgresql/data
        networks:
            - backend-network

networks:
    backend-network:
        driver: bridge